# Generated by Django 2.2 on 2020-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('technology_used', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='projects')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='skills')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=1000)),
                ('description1', models.TextField(max_length=1000)),
                ('description2', models.TextField(max_length=1000)),
                ('get_cv', models.CharField(max_length=1000)),
                ('download_cv', models.CharField(max_length=1000)),
                ('git_hub', models.CharField(max_length=1000)),
                ('linkdin', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
            ],
        ),
    ]
