# Generated by Django 2.2 on 2020-02-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('technology_used', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='pics')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
